@startuml main
class Board {
  -board : char[20,40]
  -generateWalls()
  +display()

}

class Player {
    -pos : int[2]
    -level : double
    -speed : int
    -health : int
    -hunger : int
    -wisdom : int
    -strength : int
    -rightHand : string
    -leftHand : string
    -isMoveCorrect(char m)
    -takeItem(string item)
    +moveUp()
    +moveDown()
    +moveRight()
    +moveLeft()
}

class Weapon{
    -damage : int
    -attackSpeed : float
    -twoHands : bool
    -range : bool
    +attack()
}

class Backpack{
    -storedItems : int
    -capacity : int
    -currentSpace : int
    -storage : string[]

    +put(string item)
    +get(string item)
    +drop(string item)
}

class Stick {

}
class Rock {
    
}
class Log {

}
class Sword{

}
class Gun{

}

class Laser {

}

Sword --> Weapon
Stick --> Weapon
Log --> Weapon
Gun --> Weapon
Rock --> Weapon
Laser --> Weapon

class Mineral {
    -value : int
    +getValue()
}

class Gold{

}

class Silver{

}

Silver --> Mineral
Gold --> Mineral
@enduml